from __future__ import annotations

import time

from fastapi.testclient import TestClient
from prism_api.atlas_bench_runner import FirstChoiceSubject
from prism_api.atlas_foundry_dataset import _assign_split
from prism_api.main import create_app
from prism_api_contracts import (
    AtlasPlanState,
    AtlasRunResponse,
    AtlasTrainingRecipeMethod,
    AtlasTrainingSplit,
)


def _dataset(client: TestClient) -> str:
    response = client.post(
        "/api/v1/overview/datasets",
        files={"file": ("unknown.csv", b"segment,revenue\na,10\nb,12\na,8\n", "text/csv")},
    )
    assert response.status_code == 201
    return str(response.json()["dataset_id"])


def _terminal_run(client: TestClient, run_id: str) -> AtlasRunResponse:
    for _ in range(100):
        response = client.get(f"/api/v1/atlas/runs/{run_id}")
        assert response.status_code == 200
        run = AtlasRunResponse.model_validate(response.json())
        if run.plan.state in {AtlasPlanState.COMPLETED, AtlasPlanState.FAILED, AtlasPlanState.CANCELLED}:
            return run
        time.sleep(0.01)
    raise AssertionError("Atlas run did not reach a terminal state")


def _completed_run(client: TestClient, *, objective: str = "Understand this dataset safely.") -> AtlasRunResponse:
    dataset_id = _dataset(client)
    started = client.post("/api/v1/atlas/runs", json={"dataset_id": dataset_id, "objective": objective})
    assert started.status_code == 202
    run = _terminal_run(client, started.json()["run_id"])
    assert run.plan.state is AtlasPlanState.COMPLETED
    return run


def _completed_train_split_run(client: TestClient) -> AtlasRunResponse:
    """Create genuine, distinct durable runs until the deterministic split is TRAIN.

    Dataset identifiers are intentionally generated by DatasetStore, so a
    single real run can legitimately hash into validation or test. This helper
    retains the production split policy and makes the route test exercise the
    actual TRAIN-only export path rather than weakening it.
    """
    for attempt in range(12):
        run = _completed_run(client, objective=f"Understand verified training fixture {attempt} safely.")
        if _assign_split(run.plan.dataset_id) is AtlasTrainingSplit.TRAIN:
            return run
    raise AssertionError("Could not create a deterministic TRAIN-split Atlas fixture after 12 attempts")


def test_bench_corpus_summary_never_leaks_the_answer_key() -> None:
    client = TestClient(create_app())
    response = client.get("/api/v1/atlas/bench/corpus/summary")
    assert response.status_code == 200
    body = response.json()
    assert body["total_tasks"] >= 80
    assert len(body["category_counts"]) == 10
    raw = response.text
    assert "correct_choice" not in raw
    assert "rationale" not in raw


def test_live_bench_refuses_to_fabricate_a_deterministic_provider_score() -> None:
    client = TestClient(create_app())
    response = client.post("/api/v1/atlas/bench/runs", params={"provider": "deterministic"})
    assert response.status_code == 409
    assert "does not implement general multiple-choice inference" in response.json()["detail"]


def test_live_bench_server_owns_scoring_and_persists_the_run(monkeypatch) -> None:  # type: ignore[no-untyped-def]
    from prism_api import atlas_bench_live

    monkeypatch.setattr(
        atlas_bench_live,
        "make_live_subject",
        lambda provider: FirstChoiceSubject(subject_id=f"live_test_{provider.value}"),
    )
    client = TestClient(create_app())

    response = client.post("/api/v1/atlas/bench/runs", params={"provider": "ollama"})
    assert response.status_code == 201
    run = response.json()
    assert run["subject_id"] == "live_test_ollama"
    assert run["total_tasks"] >= 80
    assert 0 <= run["total_passed"] <= run["total_tasks"]

    fetched = client.get(f"/api/v1/atlas/bench/runs/detail/{run['run_id']}")
    assert fetched.status_code == 200
    assert fetched.json()["run_id"] == run["run_id"]

    # The client still cannot supply an answer, judge, threshold or verdict.
    forbidden = client.post(
        "/api/v1/atlas/bench/runs",
        params={"provider": "ollama", "correct_choice": 0, "verdict": "promote_eligible"},
    )
    assert forbidden.status_code == 201
    assert "correct_choice" not in forbidden.text
    assert "rationale" not in forbidden.text


def test_adapter_capabilities_endpoint_is_honest() -> None:
    client = TestClient(create_app())
    response = client.get("/api/v1/atlas/adapters/capabilities")
    assert response.status_code == 200
    capabilities = response.json()
    assert len(capabilities) == 6
    assert all(item["can_hot_swap"] is False for item in capabilities)

    single = client.get("/api/v1/atlas/adapters/capabilities/atlas-sql")
    assert single.status_code == 200
    assert single.json()["adapter"] == "atlas-sql"


def test_foundry_capability_endpoint_reports_soup_absent() -> None:
    client = TestClient(create_app())
    response = client.get("/api/v1/atlas/foundry/capability")
    assert response.status_code == 200
    body = response.json()
    assert body["backend"] == "soup"
    assert body["soup_available"] is False
    assert body["can_train"] is False


def test_promotion_endpoints_are_read_only_and_never_accept_a_client_decision() -> None:
    client = TestClient(create_app())
    current = client.get("/api/v1/atlas/promotion/current")
    assert current.status_code == 200
    assert current.json() is None

    history = client.get("/api/v1/atlas/promotion/history")
    assert history.status_code == 200
    assert history.json() == []

    rollback = client.post("/api/v1/atlas/promotion/rollback", params={"reason": "test"})
    assert rollback.status_code == 409  # nothing to roll back to yet -- never fabricated


def test_training_dataset_build_and_preview_round_trip_through_the_api() -> None:
    client = TestClient(create_app())
    _completed_run(client)  # ensures at least one eligible run exists in the shared store

    built = client.post("/api/v1/atlas/foundry/training-datasets")
    assert built.status_code == 201
    manifest = built.json()
    assert manifest["train_count"] + manifest["validation_count"] + manifest["test_count"] >= 1

    listed = client.get("/api/v1/atlas/foundry/training-datasets")
    assert listed.status_code == 200
    assert any(item["version_id"] == manifest["version_id"] for item in listed.json())

    preview = client.get(f"/api/v1/atlas/foundry/training-datasets/{manifest['version_id']}/preview")
    assert preview.status_code == 200
    assert len(preview.json()) >= 1


def test_preference_dataset_build_endpoint_is_empty_without_any_real_correction() -> None:
    client = TestClient(create_app())
    built = client.post("/api/v1/atlas/foundry/preference-datasets")
    assert built.status_code == 201
    manifest = built.json()
    # No supersede() calls happened in this test -> no fabricated pairs.
    assert manifest["train_count"] + manifest["validation_count"] + manifest["test_count"] == 0


def test_starting_a_foundry_job_rejects_a_recipe_dataset_mismatch() -> None:
    client = TestClient(create_app())
    recipe = {
        "recipe_id": "recipe_test_1",
        "base_model": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        "method": AtlasTrainingRecipeMethod.QLORA.value,
        "task": "sft",
        "dataset_version_id": "trainset_mismatch",
        "created_at": "2026-01-01T00:00:00Z",
    }
    response = client.post(
        "/api/v1/atlas/foundry/jobs",
        params={"dataset_version_id": "trainset_other"},
        json=recipe,
    )
    assert response.status_code == 422


def test_starting_a_foundry_job_against_a_real_dataset_version_queues_or_fails_honestly_without_soup() -> None:
    client = TestClient(create_app())
    _completed_train_split_run(client)
    built = client.post("/api/v1/atlas/foundry/training-datasets")
    assert built.status_code == 201
    assert built.json()["train_count"] >= 1
    version_id = built.json()["version_id"]

    recipe = {
        "recipe_id": "recipe_test_2",
        "base_model": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        "method": AtlasTrainingRecipeMethod.QLORA.value,
        "task": "sft",
        "dataset_version_id": version_id,
        "created_at": "2026-01-01T00:00:00Z",
    }
    response = client.post(
        "/api/v1/atlas/foundry/jobs",
        params={"dataset_version_id": version_id},
        json=recipe,
    )
    assert response.status_code == 202
    job = response.json()
    # No `soup` binary in this environment: the job must fail honestly, not
    # pretend to train (unless capacity queued it first, also a valid state).
    assert job["state"] in {"failed", "queued"}

    fetched = client.get(f"/api/v1/atlas/foundry/jobs/{job['job_id']}")
    assert fetched.status_code == 200
    assert fetched.json()["job_id"] == job["job_id"]

    missing = client.get("/api/v1/atlas/foundry/jobs/does_not_exist")
    assert missing.status_code == 404


def test_bench_run_endpoints_404_cleanly_for_an_unknown_run() -> None:
    client = TestClient(create_app())
    response = client.get("/api/v1/atlas/bench/runs/detail/does_not_exist")
    assert response.status_code == 404
    empty_list = client.get("/api/v1/atlas/bench/runs/some_subject")
    assert empty_list.status_code == 200
    assert empty_list.json() == []
