/* This file is generated by tools/generate_typescript_contracts.py. Do not edit manually. */

export type AiAnalystOutcome = "answered" | "insufficient_evidence" | "sql_ready" | "provider_fallback";

export interface AiAnalystRequest {
  question: string;
  dataset_id?: string;
  result_run_id?: string;
  follow_up_to?: string;
}

export interface AiAnalystResponse {
  request_id: string;
  outcome: AiAnalystOutcome;
  answer: string;
  uncertainty: string;
  limiting_factors?: string[];
  recommended_next_step: string;
  evidence: AiEvidence[];
  context: AiContextPacket;
  provider: AiProviderStatus;
  sql_draft?: string;
  sql_connection_id?: string;
  provenance?: Record<string, unknown>;
}

export interface AiContextPacket {
  dataset_id: string;
  source_fingerprint: string;
  column_count: number;
  row_count: number;
  raw_sample_rows: number;
  token_budget: number;
  prompt_version: string;
  config_version: string;
  result_run_id?: string;
}

export interface AiEvidence {
  kind: "dataset" | "quality" | "column" | "correlation" | "sql_result" | "limitation";
  label: string;
  value: string;
  provenance_ref: string;
}

export type AiProviderStatus = "deterministic" | "ollama" | "fallback";

export interface AnalyticalObject {
  object_id: string;
  kind: ObjectKind;
  lifecycle: LifecycleState;
  provenance: AnalyticalProvenance;
  schema_version?: string;
  payload?: Record<string, unknown>;
}

export interface AnalyticalProvenance {
  dataset: DatasetRef;
  parent_refs?: ParentRef[];
  warnings?: string[];
  evidence_refs?: EvidenceRef[];
  reproducibility: CleaningReproducibilitySpec | StatisticalTestReproducibilitySpec | GenericReproducibilitySpec;
  created_at: string;
}

export type AtlasCleanAction = "explain_issue" | "propose_fix" | "compare_before_after";

export interface AtlasCleanRequest {
  action: AtlasCleanAction;
  issue_id?: string;
}

export interface AtlasCleanResponse {
  action: AtlasCleanAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
  proposed_operation?: CleanTransformationRequest;
}

export interface AtlasEvidence {
  label: string;
  value: string;
}

export type AtlasForecastAction = "explain_method" | "explain_trend" | "explain_seasonality" | "explain_changepoints" | "explain_intervals";

export interface AtlasForecastRequest {
  action: AtlasForecastAction;
  datetime_col: string;
  numeric_col: string;
}

export interface AtlasForecastResponse {
  action: AtlasForecastAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export type AtlasMlAction = "explain_task_type" | "compare_models" | "explain_cross_validation" | "explain_imbalance" | "explain_feature_importance" | "identify_overfitting";

export interface AtlasMlRequest {
  action: AtlasMlAction;
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
}

export interface AtlasMlResponse {
  action: AtlasMlAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export type AtlasOverviewAction = "explain_dataset" | "diagnose_quality" | "inspect_anomaly" | "suggest_next_analysis" | "trace_source" | "compare_columns" | "summarize_risks";

export interface AtlasOverviewRequest {
  action: AtlasOverviewAction;
  column?: string;
  comparison_column?: string;
}

export interface AtlasOverviewResponse {
  action: AtlasOverviewAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
  provenance: OverviewProvenance;
}

export type AtlasSqlAction = "explain_query" | "optimize_query" | "debug_error" | "inspect_plan" | "generate_sql" | "compare_queries" | "explain_selection" | "trace_lineage" | "convert_result";

export interface AtlasSqlRequest {
  action: AtlasSqlAction;
  connection_id: string;
  sql?: string;
  selected_text?: string;
  intent?: string;
  comparison_sql?: string;
}

export interface AtlasSqlResponse {
  action: AtlasSqlAction;
  summary: string;
  draft_sql?: string;
  evidence: AtlasEvidence[];
  uncertainty: string;
  executable?: boolean;
}

export type AtlasStatsAction = "explain_test" | "explain_assumptions" | "explain_effect_size" | "recommend_next_step";

export interface AtlasStatsRequest {
  action: AtlasStatsAction;
  col_a: string;
  col_b: string;
}

export interface AtlasStatsResponse {
  action: AtlasStatsAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export type AtlasVisualizeAction = "explain_chart" | "identify_anomaly" | "propose_alternative";

export interface AtlasVisualizeRequest {
  action: AtlasVisualizeAction;
  spec: VisualizationSpec;
}

export interface AtlasVisualizeResponse {
  action: AtlasVisualizeAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export interface Body_upload_dataset_api_v1_overview_datasets_post {
  file: string;
}

export interface ChangepointFinding {
  position: number;
  timestamp: string;
  before_mean: number;
  after_mean: number;
  delta: number;
  pct_change?: number;
  before_n: number;
  after_n: number;
}

export interface ChangepointRequest {
  datetime_col: string;
  numeric_col: string;
  max_changepoints?: number;
}

export interface ChangepointResult {
  datetime_col: string;
  numeric_col: string;
  observed: ForecastPoint[];
  changepoints: ChangepointFinding[];
  n_segments: number;
  verdict: string;
  provenance: OverviewProvenance;
}

export interface CleanApplyResponse {
  dataset: OverviewDataset;
  transformation: CleanTransformation;
  issues: CleanIssue[];
  health: OverviewHealth;
}

export interface CleanIssue {
  issue_id: string;
  kind: CleanIssueKind;
  column?: string;
  severity: "low" | "medium" | "high";
  affected_rows: number;
  description: string;
  suggested_operation?: CleanOperation;
}

export type CleanIssueKind = "missing_values" | "duplicate_rows" | "all_null_column" | "type_mismatch" | "outlier_burden";

export type CleanOperation = "drop_duplicates" | "fill_missing" | "drop_missing_rows" | "convert_type" | "rename_column" | "drop_column" | "trim_whitespace" | "normalize_case";

export interface CleanPreviewResponse {
  operation: CleanOperation;
  affected_rows: number;
  affected_columns?: string[];
  before_sample: Record<string, unknown>[];
  after_sample: Record<string, unknown>[];
  warnings?: string[];
  projected_health: OverviewHealth;
}

export interface CleanStateResponse {
  dataset: OverviewDataset;
  issues: CleanIssue[];
  history: CleanTransformation[];
  health: OverviewHealth;
}

export interface CleanTransformation {
  transformation_id: string;
  operation: CleanOperation;
  column?: string;
  parameters?: Record<string, unknown>;
  affected_rows: number;
  affected_columns?: string[];
  source_revision: number;
  resulting_revision: number;
  source_fingerprint: string;
  resulting_fingerprint: string;
  reversible?: boolean;
  created_at: string;
}

export interface CleanTransformationRequest {
  operation: CleanOperation;
  column?: string;
  new_name?: string;
  target_type?: "numeric" | "text" | "datetime" | "boolean";
  fill_strategy?: FillStrategy;
  fill_value?: string;
  case?: "lower" | "upper" | "title";
}

export interface CleanUndoRequest {
  to_revision: number;
}

export interface CleaningReproducibilitySpec {
  producer: Producer;
  kind?: string;
  operation: string;
  parameters?: Record<string, unknown>;
}

export interface CorrelationFinding {
  left: string;
  right: string;
  coefficient: number;
}

export interface DatasetRef {
  dataset_id: string;
  revision: number;
  source_fingerprint: string;
}

export interface DatasetRowsResponse {
  dataset: OverviewDataset;
  offset: number;
  limit: number;
  total_rows: number;
  rows: Record<string, unknown>[];
  provenance: OverviewProvenance;
}

export interface DecomposeRequest {
  datetime_col: string;
  numeric_col: string;
}

export interface DecompositionResult {
  datetime_col: string;
  numeric_col: string;
  seasonal_period: number;
  trend_strength: number;
  seasonal_strength: number;
  observed: ForecastPoint[];
  trend: ForecastPoint[];
  seasonal: ForecastPoint[];
  resid: ForecastPoint[];
  verdict: string;
  provenance: OverviewProvenance;
}

export interface DistributionBucket {
  label: unknown;
  count: number;
}

export interface EvidenceRef {
  evidence_id: string;
  kind: string;
  summary?: string;
}

export type FillStrategy = "mean" | "median" | "mode" | "constant" | "forward_fill";

export interface ForecastInterval {
  timestamp: string;
  lower: number;
  upper: number;
}

export interface ForecastMetrics {
  mae?: number;
  rmse?: number;
  mape?: number;
  holdout_points?: number;
  note?: string;
}

export interface ForecastPoint {
  timestamp: string;
  value: number;
}

export interface ForecastRequest {
  datetime_col: string;
  numeric_col: string;
  horizon?: number;
}

export interface ForecastResult {
  datetime_col: string;
  numeric_col: string;
  frequency: string;
  model_used: string;
  horizon: number;
  observed: ForecastPoint[];
  forecast: ForecastPoint[];
  intervals: ForecastInterval[];
  metrics: ForecastMetrics;
  caveat: string;
  warnings?: string[];
  provenance: OverviewProvenance;
}

export interface FreshnessAssessment {
  object_id: string;
  state: FreshnessState;
  freshness_known: boolean;
  dataset_id: string;
  object_revision: number;
  object_fingerprint: string;
  active_revision?: number;
  active_fingerprint?: string;
  reason_code: string;
  reason: string;
  assessed_at: string;
}

export type FreshnessState = "current" | "stale" | "superseded" | "unknown" | "invalid";

export interface GenericReproducibilitySpec {
  producer: Producer;
  kind?: string;
  operation: string;
  parameters?: Record<string, unknown>;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  status?: string;
  contract_version?: string;
  generated_at: string;
  migrations: MigrationState[];
}

export type LifecycleState = "draft" | "completed" | "failed" | "stale" | "archived";

export type LineageDirection = "upstream" | "downstream" | "both";

export interface LineageEdge {
  parent_object_id: string;
  child_object_id: string;
}

export interface LineageNode {
  object: AnalyticalObject;
  depth: number;
}

export interface LineagePath {
  from_object_id: string;
  to_object_id: string;
  found: boolean;
  nodes?: LineageNode[];
  edges?: LineageEdge[];
}

export interface LineageTraversal {
  root_object_id: string;
  direction: LineageDirection;
  nodes?: LineageNode[];
  edges?: LineageEdge[];
  max_depth?: number;
  truncated?: boolean;
}

export interface MigrationState {
  workflow: string;
  channel: ReleaseChannel;
  parity_required?: boolean;
  legacy_reference: string;
}

export interface MlApplyFeatureRequest {
  suggestion: MlFeatureSuggestion;
}

export interface MlApplyFeatureResponse {
  dataset: OverviewDataset;
  description: string;
  provenance: OverviewProvenance;
}

export interface MlBaselineRequest {
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
  use_smote?: boolean;
}

export interface MlBaselineResult {
  task_type: MlTaskType;
  results: Record<string, Record<string, number>>;
  confusion_matrix?: number[][];
  confusion_labels?: string[];
  feature_importances: MlFeatureImportance[];
  n_train: number;
  n_test: number;
  smote_before_after?: Record<string, unknown>;
  cv?: MlCvResult;
  cv_error?: string;
  verdict: string;
  leakage_note: string;
  provenance: OverviewProvenance;
}

export interface MlCvMetric {
  mean: number;
  std: number;
}

export interface MlCvResult {
  results: Record<string, Record<string, MlCvMetric>>;
  n_splits: number;
}

export interface MlFeatureImportance {
  feature: string;
  importance: number;
}

export interface MlFeatureRankingRow {
  feature: string;
  mutual_info: number;
  mutual_info_rank: number;
  l1_coef_abs: number;
  l1_rank: number;
  rfe_selected: boolean;
  rfe_rank: number;
  consensus_votes: number;
  consensus_rank: number;
}

export interface MlFeatureSelectionRequest {
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
  top_k?: number;
}

export interface MlFeatureSelectionResult {
  task_type: MlTaskType;
  top_k: number;
  n_features: number;
  ranking: MlFeatureRankingRow[];
  recommended_features: string[];
  provenance: OverviewProvenance;
}

export interface MlFeatureSuggestion {
  kind: MlSuggestionType;
  column?: string;
  columns?: string[];
  method?: string;
  reason: string;
}

export interface MlFeatureSuggestionsResponse {
  target_col: string;
  suggestions: MlFeatureSuggestion[];
}

export interface MlImbalanceInfo {
  target_col: string;
  counts: Record<string, number>;
  proportions_pct: Record<string, number>;
  minority_pct: number;
  is_imbalanced: boolean;
  explanation: string;
}

export interface MlShapImportance {
  feature: string;
  mean_abs_shap: number;
}

export interface MlShapRequest {
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
}

export interface MlShapResult {
  task_type: MlTaskType;
  model_explained: string;
  global_importance: MlShapImportance[];
  note: string;
  provenance: OverviewProvenance;
}

export type MlSuggestionType = "encode" | "scale" | "datetime_expand" | "interaction";

export interface MlTaskDetectionResponse {
  target_col: string;
  task_type: MlTaskType;
  reason: string;
}

export type MlTaskType = "classification" | "regression";

export interface NumericSummary {
  min?: number | string;
  max?: number | string;
  mean?: number;
  median?: number;
  skewness?: string;
  kurtosis?: string;
}

export type ObjectKind = "dataset_revision" | "profile" | "query_result" | "cleaning_plan" | "visualization" | "analysis" | "forecast" | "ml_model" | "evidence";

export interface OutlierFinding {
  count: number;
  pct: number;
}

export interface OverviewColumn {
  name: string;
  semantic_type: "numeric" | "datetime" | "categorical" | "text" | "all_null";
  missing_pct: number;
  unique_count: number;
  health: "good" | "warning" | "issue";
  issues: string[];
  warnings: string[];
  distribution: DistributionBucket[];
  numeric?: NumericSummary;
}

export interface OverviewDataset {
  dataset_id: string;
  revision: number;
  source_name: string;
  source_fingerprint: string;
  row_count: number;
  column_count: number;
}

export interface OverviewHealth {
  completeness: number;
  consistency: number;
  uniqueness: number;
  validity: number;
  outlier_burden: number;
  total: number;
}

export interface OverviewProfileResponse {
  dataset: OverviewDataset;
  provenance: OverviewProvenance;
  quality: OverviewQuality;
  health: OverviewHealth;
  columns: OverviewColumn[];
  correlations: CorrelationFinding[];
  suggestions: OverviewSuggestion[];
}

export interface OverviewProvenance {
  source_fingerprint: string;
  dataset_revision: number;
  parameters?: Record<string, unknown>;
  service_version: string;
  computed_at: string;
}

export interface OverviewQuality {
  n_rows: number;
  n_cols: number;
  missing_by_column: Record<string, number>;
  total_missing_cells: number;
  total_missing_pct: number;
  duplicate_rows: number;
  memory_usage: string;
  outliers: Record<string, OutlierFinding>;
  all_null_columns: string[];
}

export interface OverviewSuggestion {
  workflow: string;
  reason: string;
}

export interface ParentRef {
  object_id: string;
  relation?: string;
}

export interface Producer {
  service: string;
  version: string;
}

export interface ProviderReadiness {
  name: string;
  status: "configured" | "not_configured";
  detail: string;
}

export type QueryExecutionState = "queued" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out";

export type QueryRisk = "safe_read" | "governed_write" | "unknown";

export interface ReadinessResponse {
  status?: string;
  contract_version?: string;
  generated_at: string;
  providers: ProviderReadiness[];
}

export type ReleaseChannel = "legacy" | "shadow" | "enabled";

export type ReproductionMode = "same_revision" | "current_revision";

export type ReproductionOutcome = "created" | "unsupported" | "validation_failed" | "source_revision_unavailable";

export interface ReproductionResponse {
  outcome: ReproductionOutcome;
  original_object_id: string;
  mode: ReproductionMode;
  new_object?: AnalyticalObject;
  detail: string;
}

export interface RerunRequest {
  mode: ReproductionMode;
}

export interface SqlCapability {
  name: string;
  supported: boolean;
  reason?: string;
}

export interface SqlColumn {
  name: string;
  data_type: string;
  nullable: boolean;
  sample_count: number;
}

export interface SqlConnectionSummary {
  connection_id: string;
  label: string;
  source_type: SqlSourceType;
  dialect: SqlDialect;
  status: "ready" | "degraded" | "unavailable";
  capabilities: SqlCapability[];
  source_fingerprint?: string;
}

export type SqlDialect = "duckdb" | "mysql" | "postgresql" | "sqlserver" | "sqlite";

export interface SqlPlanResponse {
  connection_id: string;
  supported: boolean;
  plan?: string[];
  warning?: string;
}

export interface SqlProvenance {
  connection_id: string;
  source_fingerprint: string;
  schema_fingerprint: string;
  sql_fingerprint: string;
  sql_version?: number;
  dialect: SqlDialect;
  parameters?: Record<string, unknown>;
  service_version: string;
  executed_at: string;
  result_fingerprint?: string;
  downstream_objects?: string[];
}

export interface SqlResultColumn {
  name: string;
  data_type: string;
}

export interface SqlResultPageResponse {
  run: SqlRunResponse;
  offset: number;
  limit: number;
  rows: Record<string, unknown>[];
}

export interface SqlResultPromotionResponse {
  run: SqlRunResponse;
  dataset: OverviewDataset;
}

export interface SqlRunRequest {
  connection_id: string;
  sql: string;
  parameters?: Record<string, unknown>;
  timeout_ms?: number;
  result_limit?: number;
  client_request_id?: string;
}

export interface SqlRunResponse {
  run_id: string;
  state: QueryExecutionState;
  risk: QueryRisk;
  sql: string;
  result_columns?: SqlResultColumn[];
  row_count?: number;
  returned_row_count?: number;
  truncated?: boolean;
  duration_ms?: number;
  warnings?: string[];
  error?: string;
  provenance: SqlProvenance;
}

export interface SqlSchemaResponse {
  connection: SqlConnectionSummary;
  tables: SqlTable[];
  schema_fingerprint: string;
  warnings?: string[];
}

export interface SqlSnippet {
  snippet_id: string;
  name: string;
  sql: string;
  dialect: SqlDialect;
  parameters?: Record<string, unknown>;
  created_at: string;
}

export interface SqlSnippetCreate {
  name: string;
  sql: string;
  dialect: SqlDialect;
  parameters?: Record<string, unknown>;
}

export type SqlSourceType = "local_dataset" | "mysql" | "postgresql" | "sqlserver" | "sqlite";

export interface SqlTable {
  name: string;
  columns: SqlColumn[];
}

export interface StatNormalityCheck {
  subject: string;
  p_value?: number;
  is_normal?: boolean;
  note?: string;
}

export interface StatSuggestionResponse {
  col_a: string;
  col_b: string;
  test?: StatTestKind;
  reason?: string;
  numeric_col?: string;
  cat_col?: string;
  error?: string;
}

export type StatTestKind = "ttest" | "anova" | "chi2" | "pearson";

export interface StatTestRequest {
  test: StatTestKind;
  col_a: string;
  col_b: string;
  numeric_col?: string;
  cat_col?: string;
}

export interface StatTestResult {
  test: StatTestKind;
  statistic: number;
  p_value: number;
  effect_size: number;
  effect_size_name: string;
  effect_size_label: "negligible" | "small" | "medium" | "large";
  groups?: Record<string, number>;
  means?: Record<string, number>;
  dof?: number;
  n?: number;
  low_expected_pct?: number;
  normality?: StatNormalityCheck[];
  significant: boolean;
  interpretation: string;
  evidence_statement: string;
  warnings?: string[];
  provenance: OverviewProvenance;
}

export interface StatisticalTestReproducibilitySpec {
  producer: Producer;
  kind?: string;
  test: string;
  columns: string[];
  parameters?: Record<string, unknown>;
}

export interface ValidationError {
  loc: string | number[];
  msg: string;
  type: string;
}

export interface VisualizationDataResponse {
  spec: VisualizationSpec;
  data: VisualizationDatum[];
  truncated: boolean;
  warnings?: string[];
  provenance: OverviewProvenance;
}

export interface VisualizationDatum {
  label: string;
  value: number;
}

export interface VisualizationSpec {
  mark: VizMark;
  intent: VizIntent;
  dimension?: string;
  measure?: string;
  aggregation: VizAggregation;
  filters?: Record<string, unknown>;
  max_categories?: number;
}

export interface VisualizationSuggestion {
  spec: VisualizationSpec;
  rationale: string;
  alternatives?: VizMark[];
}

export type VizAggregation = "count" | "sum" | "mean" | "median" | "none";

export type VizIntent = "comparison" | "distribution" | "relationship" | "composition" | "trend" | "ranking";

export type VizMark = "bar" | "line" | "scatter" | "histogram" | "box";

export interface ApiTransport {
  request<TResponse>(request: ApiRequest): Promise<TResponse>;
  subscribe(request: SseRequest): AsyncIterable<SseEvent>;
}

export interface ApiRequest {
  path: string;
  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  body?: unknown;
  signal?: AbortSignal;
}

export interface SseRequest {
  path: string;
  signal?: AbortSignal;
}

export interface SseEvent {
  event: string;
  id?: string;
  data: unknown;
}

export class PlatformApiClient {
  public constructor(private readonly transport: ApiTransport) {}

  public health(): Promise<HealthResponse> {
    return this.transport.request<HealthResponse>({ path: "/api/v1/platform/health" });
  }

  public events(signal?: AbortSignal): AsyncIterable<SseEvent> {
    return this.transport.subscribe({ path: "/api/v1/platform/events", ...(signal ? { signal } : {}) });
  }
}
