/* This file is generated by tools/generate_typescript_contracts.py. Do not edit manually. */

export type AiAnalystOutcome = "answered" | "insufficient_evidence" | "sql_ready" | "provider_fallback";

export interface AiAnalystRequest {
  question: string;
  dataset_id?: string;
  result_run_id?: string;
  follow_up_to?: string;
}

export interface AiAnalystResponse {
  request_id: string;
  outcome: AiAnalystOutcome;
  answer: string;
  uncertainty: string;
  limiting_factors?: string[];
  recommended_next_step: string;
  evidence: AiEvidence[];
  context: AiContextPacket;
  provider: AiProviderStatus;
  sql_draft?: string;
  sql_connection_id?: string;
  provenance?: Record<string, unknown>;
}

export interface AiContextPacket {
  dataset_id: string;
  source_fingerprint: string;
  column_count: number;
  row_count: number;
  raw_sample_rows: number;
  token_budget: number;
  prompt_version: string;
  config_version: string;
  result_run_id?: string;
}

export interface AiEvidence {
  kind: "dataset" | "quality" | "column" | "correlation" | "sql_result" | "limitation";
  label: string;
  value: string;
  provenance_ref: string;
}

export type AiProviderStatus = "deterministic" | "ollama" | "fallback";

export interface AnalyticalAuditEvent {
  event_id: string;
  object_id: string;
  event_type: string;
  actor: string;
  producer_service: string;
  producer_version: string;
  request_id?: string;
  created_at: string;
}

export interface AnalyticalObject {
  object_id: string;
  kind: ObjectKind;
  lifecycle: LifecycleState;
  provenance: AnalyticalProvenance;
  schema_version?: string;
  payload?: Record<string, unknown>;
}

export interface AnalyticalProvenance {
  dataset: DatasetRef;
  parent_refs?: ParentRef[];
  warnings?: string[];
  evidence_refs?: EvidenceRef[];
  reproducibility: CleaningReproducibilitySpec | StatisticalTestReproducibilitySpec | GenericReproducibilitySpec;
  created_at: string;
}

export interface AtlasAdapterCapability {
  adapter: AtlasAdapterId;
  can_load: boolean;
  can_unload: boolean;
  can_hot_swap: boolean;
  memory_cost_mb?: number;
  compatible_base_models?: string[];
  detail: string;
}

export type AtlasAdapterId = "atlas-core" | "atlas-sql" | "atlas-statistics" | "atlas-ml" | "atlas-forecast" | "atlas-research";

export type AtlasBenchCategory = "sql" | "statistics" | "machine_learning" | "forecasting" | "causal_safety" | "agentic" | "evidence" | "python_sandbox" | "personality" | "general";

export interface AtlasBenchCategoryCount {
  category: AtlasBenchCategory;
  task_count: number;
}

export interface AtlasBenchCategoryScore {
  category: AtlasBenchCategory;
  total: number;
  passed: number;
}

export interface AtlasBenchCorpusSummary {
  corpus_version: string;
  corpus_hash: string;
  total_tasks: number;
  category_counts?: AtlasBenchCategoryCount[];
}

export interface AtlasBenchSuiteRun {
  run_id: string;
  subject_id: string;
  corpus_version: string;
  corpus_hash: string;
  total_tasks: number;
  total_passed: number;
  category_scores?: AtlasBenchCategoryScore[];
  started_at: string;
  completed_at: string;
}

export interface AtlasBenchTaskResult {
  task_id: string;
  category: AtlasBenchCategory;
  subject_id: string;
  chosen_choice?: number;
  correct: boolean;
  raw_answer?: string;
  evaluated_at: string;
}

export interface AtlasCandidateArtifact {
  candidate_id: string;
  job_id: string;
  recipe_id: string;
  base_model: string;
  method: AtlasTrainingRecipeMethod;
  adapter_path: string;
  dataset_version_id: string;
  created_at: string;
}

export type AtlasCleanAction = "explain_issue" | "propose_fix" | "compare_before_after";

export interface AtlasCleanRequest {
  action: AtlasCleanAction;
  issue_id?: string;
}

export interface AtlasCleanResponse {
  action: AtlasCleanAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
  proposed_operation?: CleanTransformationRequest;
}

export interface AtlasCouncilConclusion {
  specialist: AtlasSpecialistId;
  conclusion: string;
  confidence: "low" | "medium" | "high";
  objections?: string[];
  evidence?: AtlasEvidenceReference[];
}

export interface AtlasEvidence {
  label: string;
  value: string;
}

export interface AtlasEvidenceReference {
  evidence_id: string;
  kind: "dataset_revision" | "overview_profile" | "analytical_object" | "tool_output" | "web_research" | "memory" | "project_knowledge";
  summary: string;
  dataset_id?: string;
  dataset_revision?: number;
  source_fingerprint?: string;
}

export type AtlasForecastAction = "explain_method" | "explain_trend" | "explain_seasonality" | "explain_changepoints" | "explain_intervals";

export interface AtlasForecastRequest {
  action: AtlasForecastAction;
  datetime_col: string;
  numeric_col: string;
}

export interface AtlasForecastResponse {
  action: AtlasForecastAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export type AtlasFoundryBackendName = "soup" | "mock";

export interface AtlasFoundryCapability {
  backend: AtlasFoundryBackendName;
  soup_available: boolean;
  soup_version?: string;
  can_train: boolean;
  can_cancel: boolean;
  can_pause?: boolean;
  detail: string;
}

export interface AtlasFoundryPreflight {
  compatible: boolean;
  estimated_total_memory_gb?: number;
  estimated_tokens_per_sec?: number;
  recommended_batch_size?: number;
  detail: string;
}

export interface AtlasKnowledgeChunk {
  chunk_id: string;
  project_id: string;
  source_ref: string;
  content_version: string;
  location: string;
  content: string;
  injection_detected?: boolean;
  score?: number;
}

export interface AtlasKnowledgeSearchRequest {
  project_id: string;
  query: string;
  limit?: number;
}

export interface AtlasKnowledgeSourceRequest {
  project_id: string;
  source_ref: string;
  content: string;
  content_version: string;
  kind: "markdown" | "text" | "python" | "sql" | "notebook_metadata" | "documentation";
}

export type AtlasLineageAction = "explain_provenance" | "explain_staleness" | "explain_lineage" | "compare_versions" | "recommend_reruns" | "explain_evidence";

export interface AtlasLineageRequest {
  action: AtlasLineageAction;
  compare_to_object_id?: string;
}

export interface AtlasLineageResponse {
  action: AtlasLineageAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
  limitation?: string;
}

export type AtlasMemoryClass = "data_evidence" | "project_knowledge" | "user_memory" | "model_knowledge" | "web_research";

export interface AtlasMemoryRecord {
  memory_id: string;
  scope: AtlasMemoryScope;
  knowledge_class: AtlasMemoryClass;
  content: string;
  source: string;
  confidence: "low" | "medium" | "high";
  timestamp: string;
  source_ref?: string;
  workspace_id?: string;
  sensitivity?: "public" | "internal" | "private" | "restricted";
  user_editable?: boolean;
  deletable?: boolean;
  provenance?: AtlasEvidenceReference[];
  reinforcement?: number;
  last_used?: string;
  contradictions?: string[];
  superseded_by?: string;
  project_id?: string;
  created_at?: string;
  updated_at?: string;
  last_used_at?: string;
}

export type AtlasMemoryScope = "session" | "project" | "workspace" | "global";

export interface AtlasMemoryWriteRequest {
  scope: AtlasMemoryScope;
  knowledge_class: AtlasMemoryClass;
  content: string;
  source: string;
  source_ref?: string;
  confidence?: "low" | "medium" | "high";
  project_id?: string;
  workspace_id?: string;
  sensitivity?: "public" | "internal" | "private" | "restricted";
  user_editable?: boolean;
  provenance?: AtlasEvidenceReference[];
}

export type AtlasMlAction = "explain_task_type" | "compare_models" | "explain_cross_validation" | "explain_imbalance" | "explain_feature_importance" | "identify_overfitting";

export interface AtlasMlRequest {
  action: AtlasMlAction;
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
}

export interface AtlasMlResponse {
  action: AtlasMlAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export interface AtlasModelProviderCapabilities {
  provider: AtlasModelProviderName;
  available: boolean;
  capabilities?: AtlasProviderCapability[];
  raw_data_policy?: "never" | "explicitly_authorized";
  detail: string;
}

export type AtlasModelProviderName = "deterministic" | "ollama";

export type AtlasOverviewAction = "explain_dataset" | "diagnose_quality" | "inspect_anomaly" | "suggest_next_analysis" | "trace_source" | "compare_columns" | "summarize_risks";

export interface AtlasOverviewRequest {
  action: AtlasOverviewAction;
  column?: string;
  comparison_column?: string;
}

export interface AtlasOverviewResponse {
  action: AtlasOverviewAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
  provenance: OverviewProvenance;
}

export type AtlasPlanState = "draft" | "running" | "completed" | "failed" | "cancelled";

export interface AtlasPlanStep {
  step_id: string;
  title: string;
  kind: AtlasStepKind;
  specialist: AtlasSpecialistId;
  tool_name: string;
  rationale?: string;
  dependencies?: string[];
  tool_args?: Record<string, unknown>;
  expected_evidence?: string[];
  state?: AtlasStepState;
  max_attempts?: number;
  attempts?: number;
  requires_approval?: boolean;
  evidence?: AtlasEvidenceReference[];
  error?: string;
}

export interface AtlasPreferenceDatasetVersion {
  version_id: string;
  created_at: string;
  source_count: number;
  excluded_count: number;
  train_count: number;
  validation_count: number;
  test_count: number;
  content_hash: string;
}

export interface AtlasPreferencePair {
  pair_id: string;
  source: AtlasPreferencePairSource;
  rejected_memory_id: string;
  chosen_memory_id: string;
  project_id?: string;
  prompt_context: string;
  rejected_response: string;
  chosen_response: string;
  evaluator_label: string;
  split: AtlasTrainingSplit;
  content_hash: string;
  created_at: string;
}

export type AtlasPreferencePairSource = "memory_supersession";

export interface AtlasProductionPointer {
  event_id: string;
  candidate_id: string;
  previous_candidate_id?: string;
  decision_id?: string;
  is_rollback?: boolean;
  reason: string;
  promoted_at: string;
}

export type AtlasProviderCapability = "structured_planning" | "local_inference" | "streaming";

export interface AtlasResearchRequest {
  query: string;
  url?: string;
  project_id?: string;
  offline?: boolean;
}

export interface AtlasResearchResult {
  research_id: string;
  query: string;
  status: "completed" | "blocked" | "offline" | "failed";
  source_url?: string;
  title?: string;
  retrieved_at: string;
  content_hash?: string;
  excerpt?: string;
  citations?: AtlasEvidenceReference[];
  injection_detected?: boolean;
  detail: string;
}

export interface AtlasResourceLease {
  lease_id: string;
  workload: AtlasResourceWorkload;
  state: "active" | "queued" | "preempted" | "released" | "cancelled";
  granted_at?: string;
  reason: string;
}

export interface AtlasResourceLeaseRequest {
  workload: AtlasResourceWorkload;
  allow_preemption?: boolean;
}

export type AtlasResourcePriority = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export interface AtlasResourceSnapshot {
  cpu_count: number;
  memory_total_mb?: number;
  memory_available_mb?: number;
  storage_free_mb?: number;
  gpu_available?: boolean;
  gpu_name?: string;
  vram_total_mb?: number;
  gpu_telemetry_detail: string;
  active_leases?: AtlasResourceLease[];
}

export interface AtlasResourceWorkload {
  workload_id: string;
  priority: AtlasResourcePriority;
  cancellable?: boolean;
  description: string;
  requires_gpu?: boolean;
  cpu_slots?: number;
  memory_mb?: number;
}

export interface AtlasRunEvent {
  event_id: string;
  run_id: string;
  sequence: number;
  type: AtlasRunEventType;
  occurred_at: string;
  specialist?: AtlasSpecialistId;
  step_id?: string;
  payload?: Record<string, unknown>;
}

export type AtlasRunEventType = "run_created" | "plan_created" | "step_started" | "step_completed" | "council_conclusion" | "run_completed" | "run_failed" | "run_cancelled";

export interface AtlasRunRequest {
  dataset_id: string;
  objective: string;
  idempotency_key?: string;
}

export interface AtlasRunResponse {
  run_id: string;
  plan: AtlasStructuredPlan;
  answer?: string;
  uncertainty?: string;
  evidence?: AtlasEvidenceReference[];
  council?: AtlasCouncilConclusion[];
  events?: AtlasRunEvent[];
  cancellation_requested?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface AtlasSandboxArtifact {
  artifact_id: string;
  filename: string;
  media_type: string;
  byte_count: number;
  sha256: string;
}

export type AtlasSandboxErrorKind = "policy" | "path" | "network" | "timeout" | "cancelled" | "resource_limit" | "execution";

export interface AtlasSandboxExecutionRequest {
  code: string;
  timeout_ms?: number;
  seed?: number;
}

export interface AtlasSandboxExecutionResult {
  execution_id: string;
  state: "completed" | "failed" | "cancelled" | "timed_out";
  stdout?: string;
  stderr?: string;
  artifacts?: AtlasSandboxArtifact[];
  error_kind?: AtlasSandboxErrorKind;
  error?: string;
  duration_ms: number;
  limits_enforced?: string[];
}

export interface AtlasSandboxWorkerHealth {
  state: "ready" | "degraded";
  execution_mode: "native_worker" | "container_worker";
  network_policy: string;
  process_tree_termination: boolean;
  cpu_quota_enforced: boolean;
  memory_quota_enforced: boolean;
  container_available: boolean;
  detail: string;
}

export type AtlasSpecialistId = "atlas" | "scout" | "curator" | "query" | "stat" | "forge" | "oracle" | "lens" | "researcher" | "librarian" | "auditor";

export interface AtlasSpecialistIdentity {
  specialist: AtlasSpecialistId;
  display_name: string;
  role: string;
  visible?: boolean;
  speaks_to_user?: boolean;
}

export type AtlasSqlAction = "explain_query" | "optimize_query" | "debug_error" | "inspect_plan" | "generate_sql" | "compare_queries" | "explain_selection" | "trace_lineage" | "convert_result";

export interface AtlasSqlRequest {
  action: AtlasSqlAction;
  connection_id: string;
  sql?: string;
  selected_text?: string;
  intent?: string;
  comparison_sql?: string;
}

export interface AtlasSqlResponse {
  action: AtlasSqlAction;
  summary: string;
  draft_sql?: string;
  evidence: AtlasEvidence[];
  uncertainty: string;
  executable?: boolean;
}

export type AtlasStatsAction = "explain_test" | "explain_assumptions" | "explain_effect_size" | "recommend_next_step";

export interface AtlasStatsRequest {
  action: AtlasStatsAction;
  col_a: string;
  col_b: string;
}

export interface AtlasStatsResponse {
  action: AtlasStatsAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export type AtlasStepKind = "profile_dataset" | "data_quality" | "sql_question" | "methodology_review" | "statistical_analysis" | "forecast" | "machine_learning" | "visualization" | "explain_history" | "python_analysis" | "research" | "audit_evidence";

export type AtlasStepState = "pending" | "running" | "completed" | "failed" | "cancelled" | "blocked";

export interface AtlasStructuredPlan {
  plan_id: string;
  objective: string;
  dataset_id: string;
  state?: AtlasPlanState;
  provider: AtlasModelProviderName;
  steps: AtlasPlanStep[];
  created_at: string;
}

export interface AtlasTrainingDatasetVersion {
  version_id: string;
  created_at: string;
  source_run_count: number;
  excluded_count: number;
  train_count: number;
  validation_count: number;
  test_count: number;
  content_hash: string;
}

export interface AtlasTrainingExample {
  example_id: string;
  source: AtlasTrainingExampleSource;
  source_run_id: string;
  dataset_id: string;
  split: AtlasTrainingSplit;
  user_request: string;
  dataset_metadata?: Record<string, unknown>;
  plan_steps?: AtlasPlanStep[];
  evidence?: AtlasEvidenceReference[];
  council?: AtlasCouncilConclusion[];
  final_answer: string;
  uncertainty?: string;
  quality_label: string;
  content_hash: string;
  created_at: string;
}

export type AtlasTrainingExampleSource = "atlas_run";

export interface AtlasTrainingJob {
  job_id: string;
  recipe_id: string;
  backend: AtlasFoundryBackendName;
  state: AtlasTrainingJobState;
  resource_lease_id?: string;
  process_id?: number;
  workspace_path?: string;
  error?: string;
  started_at?: string;
  completed_at?: string;
  created_at: string;
  updated_at: string;
}

export type AtlasTrainingJobState = "queued" | "running" | "completed" | "failed" | "cancelled";

export interface AtlasTrainingRecipe {
  recipe_id: string;
  base_model: string;
  method: AtlasTrainingRecipeMethod;
  task: "sft" | "dpo";
  dataset_version_id: string;
  quantization?: "none" | "4bit" | "8bit";
  lora_r?: number;
  lora_alpha?: number;
  lora_dropout?: number;
  target_modules?: string[];
  epochs?: number;
  learning_rate?: number;
  batch_size?: number;
  gradient_accumulation_steps?: number;
  max_length?: number;
  seed?: number;
  stream_layers?: boolean;
  recipe_version?: string;
  created_at: string;
}

export type AtlasTrainingRecipeMethod = "lora" | "qlora";

export type AtlasTrainingSplit = "train" | "validation" | "test";

export type AtlasVisualizeAction = "explain_chart" | "identify_anomaly" | "propose_alternative";

export interface AtlasVisualizeRequest {
  action: AtlasVisualizeAction;
  spec: VisualizationSpec;
}

export interface AtlasVisualizeResponse {
  action: AtlasVisualizeAction;
  summary: string;
  uncertainty: string;
  evidence: AtlasEvidence[];
}

export interface Body_upload_dataset_api_v1_overview_datasets_post {
  file: string;
}

export interface ChangepointFinding {
  position: number;
  timestamp: string;
  before_mean: number;
  after_mean: number;
  delta: number;
  pct_change?: number;
  before_n: number;
  after_n: number;
}

export interface ChangepointRequest {
  datetime_col: string;
  numeric_col: string;
  max_changepoints?: number;
}

export interface ChangepointResult {
  datetime_col: string;
  numeric_col: string;
  observed: ForecastPoint[];
  changepoints: ChangepointFinding[];
  n_segments: number;
  verdict: string;
  provenance: OverviewProvenance;
}

export interface CleanApplyResponse {
  dataset: OverviewDataset;
  transformation: CleanTransformation;
  issues: CleanIssue[];
  health: OverviewHealth;
}

export interface CleanIssue {
  issue_id: string;
  kind: CleanIssueKind;
  column?: string;
  severity: "low" | "medium" | "high";
  affected_rows: number;
  description: string;
  suggested_operation?: CleanOperation;
}

export type CleanIssueKind = "missing_values" | "duplicate_rows" | "all_null_column" | "type_mismatch" | "outlier_burden";

export type CleanOperation = "drop_duplicates" | "fill_missing" | "drop_missing_rows" | "convert_type" | "rename_column" | "drop_column" | "trim_whitespace" | "normalize_case";

export interface CleanPreviewResponse {
  operation: CleanOperation;
  affected_rows: number;
  affected_columns?: string[];
  before_sample: Record<string, unknown>[];
  after_sample: Record<string, unknown>[];
  warnings?: string[];
  projected_health: OverviewHealth;
}

export interface CleanStateResponse {
  dataset: OverviewDataset;
  issues: CleanIssue[];
  history: CleanTransformation[];
  health: OverviewHealth;
}

export interface CleanTransformation {
  transformation_id: string;
  operation: CleanOperation;
  column?: string;
  parameters?: Record<string, unknown>;
  affected_rows: number;
  affected_columns?: string[];
  source_revision: number;
  resulting_revision: number;
  source_fingerprint: string;
  resulting_fingerprint: string;
  reversible?: boolean;
  created_at: string;
}

export interface CleanTransformationRequest {
  operation: CleanOperation;
  column?: string;
  new_name?: string;
  target_type?: "numeric" | "text" | "datetime" | "boolean";
  fill_strategy?: FillStrategy;
  fill_value?: string;
  case?: "lower" | "upper" | "title";
}

export interface CleanUndoRequest {
  to_revision: number;
}

export interface CleaningReproducibilitySpec {
  producer: Producer;
  kind?: string;
  operation: string;
  parameters?: Record<string, unknown>;
}

export interface CorrelationFinding {
  left: string;
  right: string;
  coefficient: number;
}

export interface CortexEdge {
  edge_id: string;
  source_node_id: string;
  target_node_id: string;
  relation: "contains" | "executed_by" | "produced" | "supports" | "uses" | "generated_by";
}

export interface CortexGraphState {
  run_id: string;
  nodes?: CortexNode[];
  edges?: CortexEdge[];
  generated_at: string;
}

export interface CortexNode {
  node_id: string;
  kind: CortexNodeKind;
  label: string;
  state: string;
  source_id: string;
}

export type CortexNodeKind = "run" | "plan_step" | "specialist" | "evidence" | "dataset" | "analytical_object" | "tool" | "artifact";

export interface DatasetRef {
  dataset_id: string;
  revision: number;
  source_fingerprint: string;
}

export interface DatasetRowsResponse {
  dataset: OverviewDataset;
  offset: number;
  limit: number;
  total_rows: number;
  rows: Record<string, unknown>[];
  provenance: OverviewProvenance;
}

export interface DecomposeRequest {
  datetime_col: string;
  numeric_col: string;
}

export interface DecompositionResult {
  datetime_col: string;
  numeric_col: string;
  seasonal_period: number;
  trend_strength: number;
  seasonal_strength: number;
  observed: ForecastPoint[];
  trend: ForecastPoint[];
  seasonal: ForecastPoint[];
  resid: ForecastPoint[];
  verdict: string;
  provenance: OverviewProvenance;
}

export interface DistributionBucket {
  label: unknown;
  count: number;
}

export interface EvidenceRef {
  evidence_id: string;
  kind: string;
  summary?: string;
}

export type FillStrategy = "mean" | "median" | "mode" | "constant" | "forward_fill";

export interface ForecastInterval {
  timestamp: string;
  lower: number;
  upper: number;
}

export interface ForecastMetrics {
  mae?: number;
  rmse?: number;
  mape?: number;
  holdout_points?: number;
  note?: string;
}

export interface ForecastPoint {
  timestamp: string;
  value: number;
}

export interface ForecastRequest {
  datetime_col: string;
  numeric_col: string;
  horizon?: number;
}

export interface ForecastResult {
  datetime_col: string;
  numeric_col: string;
  frequency: string;
  model_used: string;
  horizon: number;
  observed: ForecastPoint[];
  forecast: ForecastPoint[];
  intervals: ForecastInterval[];
  metrics: ForecastMetrics;
  caveat: string;
  warnings?: string[];
  provenance: OverviewProvenance;
}

export interface FreshnessAssessment {
  object_id: string;
  state: FreshnessState;
  freshness_known: boolean;
  dataset_id: string;
  object_revision: number;
  object_fingerprint: string;
  active_revision?: number;
  active_fingerprint?: string;
  reason_code: string;
  reason: string;
  assessed_at: string;
}

export type FreshnessState = "current" | "stale" | "superseded" | "unknown" | "invalid";

export interface GenericReproducibilitySpec {
  producer: Producer;
  kind?: string;
  operation: string;
  parameters?: Record<string, unknown>;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  status?: string;
  contract_version?: string;
  generated_at: string;
  migrations: MigrationState[];
}

export type LifecycleState = "draft" | "completed" | "failed" | "stale" | "archived";

export type LineageDirection = "upstream" | "downstream" | "both";

export interface LineageEdge {
  parent_object_id: string;
  child_object_id: string;
}

export interface LineageNode {
  object: AnalyticalObject;
  depth: number;
}

export interface LineagePath {
  from_object_id: string;
  to_object_id: string;
  found: boolean;
  nodes?: LineageNode[];
  edges?: LineageEdge[];
}

export interface LineageTraversal {
  root_object_id: string;
  direction: LineageDirection;
  nodes?: LineageNode[];
  edges?: LineageEdge[];
  max_depth?: number;
  truncated?: boolean;
}

export interface MigrationState {
  workflow: string;
  channel: ReleaseChannel;
  parity_required?: boolean;
  legacy_reference: string;
}

export interface MlApplyFeatureRequest {
  suggestion: MlFeatureSuggestion;
}

export interface MlApplyFeatureResponse {
  dataset: OverviewDataset;
  description: string;
  provenance: OverviewProvenance;
}

export interface MlBaselineRequest {
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
  use_smote?: boolean;
}

export interface MlBaselineResult {
  task_type: MlTaskType;
  results: Record<string, Record<string, number>>;
  confusion_matrix?: number[][];
  confusion_labels?: string[];
  feature_importances: MlFeatureImportance[];
  n_train: number;
  n_test: number;
  smote_before_after?: Record<string, unknown>;
  cv?: MlCvResult;
  cv_error?: string;
  verdict: string;
  leakage_note: string;
  provenance: OverviewProvenance;
}

export interface MlCvMetric {
  mean: number;
  std: number;
}

export interface MlCvResult {
  results: Record<string, Record<string, MlCvMetric>>;
  n_splits: number;
}

export interface MlFeatureImportance {
  feature: string;
  importance: number;
}

export interface MlFeatureRankingRow {
  feature: string;
  mutual_info: number;
  mutual_info_rank: number;
  l1_coef_abs: number;
  l1_rank: number;
  rfe_selected: boolean;
  rfe_rank: number;
  consensus_votes: number;
  consensus_rank: number;
}

export interface MlFeatureSelectionRequest {
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
  top_k?: number;
}

export interface MlFeatureSelectionResult {
  task_type: MlTaskType;
  top_k: number;
  n_features: number;
  ranking: MlFeatureRankingRow[];
  recommended_features: string[];
  provenance: OverviewProvenance;
}

export interface MlFeatureSuggestion {
  kind: MlSuggestionType;
  column?: string;
  columns?: string[];
  method?: string;
  reason: string;
}

export interface MlFeatureSuggestionsResponse {
  target_col: string;
  suggestions: MlFeatureSuggestion[];
}

export interface MlImbalanceInfo {
  target_col: string;
  counts: Record<string, number>;
  proportions_pct: Record<string, number>;
  minority_pct: number;
  is_imbalanced: boolean;
  explanation: string;
}

export interface MlShapImportance {
  feature: string;
  mean_abs_shap: number;
}

export interface MlShapRequest {
  feature_cols: string[];
  target_col: string;
  task_type?: MlTaskType;
}

export interface MlShapResult {
  task_type: MlTaskType;
  model_explained: string;
  global_importance: MlShapImportance[];
  note: string;
  provenance: OverviewProvenance;
}

export type MlSuggestionType = "encode" | "scale" | "datetime_expand" | "interaction";

export interface MlTaskDetectionResponse {
  target_col: string;
  task_type: MlTaskType;
  reason: string;
}

export type MlTaskType = "classification" | "regression";

export interface NumericSummary {
  min?: number | string;
  max?: number | string;
  mean?: number;
  median?: number;
  skewness?: string;
  kurtosis?: string;
}

export type ObjectKind = "dataset_revision" | "profile" | "query_result" | "cleaning_plan" | "visualization" | "analysis" | "forecast" | "ml_model" | "evidence";

export interface OutlierFinding {
  count: number;
  pct: number;
}

export interface OverviewColumn {
  name: string;
  semantic_type: "numeric" | "datetime" | "categorical" | "text" | "all_null";
  missing_pct: number;
  unique_count: number;
  health: "good" | "warning" | "issue";
  issues: string[];
  warnings: string[];
  distribution: DistributionBucket[];
  numeric?: NumericSummary;
}

export interface OverviewDataset {
  dataset_id: string;
  revision: number;
  source_name: string;
  source_fingerprint: string;
  row_count: number;
  column_count: number;
}

export interface OverviewHealth {
  completeness: number;
  consistency: number;
  uniqueness: number;
  validity: number;
  outlier_burden: number;
  total: number;
}

export interface OverviewProfileResponse {
  dataset: OverviewDataset;
  provenance: OverviewProvenance;
  quality: OverviewQuality;
  health: OverviewHealth;
  columns: OverviewColumn[];
  correlations: CorrelationFinding[];
  suggestions: OverviewSuggestion[];
}

export interface OverviewProvenance {
  source_fingerprint: string;
  dataset_revision: number;
  parameters?: Record<string, unknown>;
  service_version: string;
  computed_at: string;
}

export interface OverviewQuality {
  n_rows: number;
  n_cols: number;
  missing_by_column: Record<string, number>;
  total_missing_cells: number;
  total_missing_pct: number;
  duplicate_rows: number;
  memory_usage: string;
  outliers: Record<string, OutlierFinding>;
  all_null_columns: string[];
}

export interface OverviewSuggestion {
  workflow: string;
  reason: string;
}

export interface ParentRef {
  object_id: string;
  relation?: string;
}

export interface Producer {
  service: string;
  version: string;
}

export interface ProviderReadiness {
  name: string;
  status: "configured" | "not_configured" | "ready" | "unavailable";
  detail: string;
}

export type QueryExecutionState = "queued" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out";

export type QueryRisk = "safe_read" | "governed_write" | "unknown";

export interface ReadinessResponse {
  status?: string;
  contract_version?: string;
  generated_at: string;
  providers: ProviderReadiness[];
}

export type ReleaseChannel = "legacy" | "shadow" | "enabled";

export type ReproductionMode = "same_revision" | "current_revision";

export type ReproductionOutcome = "created" | "unsupported" | "validation_failed" | "source_revision_unavailable";

export interface ReproductionResponse {
  outcome: ReproductionOutcome;
  original_object_id: string;
  mode: ReproductionMode;
  new_object?: AnalyticalObject;
  detail: string;
}

export interface RerunRequest {
  mode: ReproductionMode;
}

export interface SqlCapability {
  name: string;
  supported: boolean;
  reason?: string;
}

export interface SqlColumn {
  name: string;
  data_type: string;
  nullable: boolean;
  sample_count: number;
}

export interface SqlConnectionSummary {
  connection_id: string;
  label: string;
  source_type: SqlSourceType;
  dialect: SqlDialect;
  status: "ready" | "degraded" | "unavailable";
  capabilities: SqlCapability[];
  source_fingerprint?: string;
}

export type SqlDialect = "duckdb" | "mysql" | "postgresql" | "sqlserver" | "sqlite";

export interface SqlPlanResponse {
  connection_id: string;
  supported: boolean;
  plan?: string[];
  warning?: string;
}

export interface SqlProvenance {
  connection_id: string;
  source_fingerprint: string;
  schema_fingerprint: string;
  sql_fingerprint: string;
  sql_version?: number;
  dialect: SqlDialect;
  parameters?: Record<string, unknown>;
  service_version: string;
  executed_at: string;
  result_fingerprint?: string;
  downstream_objects?: string[];
}

export interface SqlResultColumn {
  name: string;
  data_type: string;
}

export interface SqlResultPageResponse {
  run: SqlRunResponse;
  offset: number;
  limit: number;
  rows: Record<string, unknown>[];
}

export interface SqlResultPromotionResponse {
  run: SqlRunResponse;
  dataset: OverviewDataset;
}

export interface SqlRunRequest {
  connection_id: string;
  sql: string;
  parameters?: Record<string, unknown>;
  timeout_ms?: number;
  result_limit?: number;
  client_request_id?: string;
}

export interface SqlRunResponse {
  run_id: string;
  state: QueryExecutionState;
  risk: QueryRisk;
  sql: string;
  result_columns?: SqlResultColumn[];
  row_count?: number;
  returned_row_count?: number;
  truncated?: boolean;
  duration_ms?: number;
  warnings?: string[];
  error?: string;
  provenance: SqlProvenance;
}

export interface SqlSchemaResponse {
  connection: SqlConnectionSummary;
  tables: SqlTable[];
  schema_fingerprint: string;
  warnings?: string[];
}

export interface SqlSnippet {
  snippet_id: string;
  name: string;
  sql: string;
  dialect: SqlDialect;
  parameters?: Record<string, unknown>;
  created_at: string;
}

export interface SqlSnippetCreate {
  name: string;
  sql: string;
  dialect: SqlDialect;
  parameters?: Record<string, unknown>;
}

export type SqlSourceType = "local_dataset" | "mysql" | "postgresql" | "sqlserver" | "sqlite";

export interface SqlTable {
  name: string;
  columns: SqlColumn[];
}

export interface StatNormalityCheck {
  subject: string;
  p_value?: number;
  is_normal?: boolean;
  note?: string;
}

export interface StatSuggestionResponse {
  col_a: string;
  col_b: string;
  test?: StatTestKind;
  reason?: string;
  numeric_col?: string;
  cat_col?: string;
  error?: string;
}

export type StatTestKind = "ttest" | "anova" | "chi2" | "pearson";

export interface StatTestRequest {
  test: StatTestKind;
  col_a: string;
  col_b: string;
  numeric_col?: string;
  cat_col?: string;
}

export interface StatTestResult {
  test: StatTestKind;
  statistic: number;
  p_value: number;
  effect_size: number;
  effect_size_name: string;
  effect_size_label: "negligible" | "small" | "medium" | "large";
  groups?: Record<string, number>;
  means?: Record<string, number>;
  dof?: number;
  n?: number;
  low_expected_pct?: number;
  normality?: StatNormalityCheck[];
  significant: boolean;
  interpretation: string;
  evidence_statement: string;
  warnings?: string[];
  provenance: OverviewProvenance;
}

export interface StatisticalTestReproducibilitySpec {
  producer: Producer;
  kind?: string;
  test: string;
  columns: string[];
  parameters?: Record<string, unknown>;
}

export interface ValidationError {
  loc: string | number[];
  msg: string;
  type: string;
}

export interface VisualizationDataResponse {
  spec: VisualizationSpec;
  data: VisualizationDatum[];
  truncated: boolean;
  warnings?: string[];
  provenance: OverviewProvenance;
}

export interface VisualizationDatum {
  label: string;
  value: number;
}

export interface VisualizationSpec {
  mark: VizMark;
  intent: VizIntent;
  dimension?: string;
  measure?: string;
  aggregation: VizAggregation;
  filters?: Record<string, unknown>;
  max_categories?: number;
}

export interface VisualizationSuggestion {
  spec: VisualizationSpec;
  rationale: string;
  alternatives?: VizMark[];
}

export type VizAggregation = "count" | "sum" | "mean" | "median" | "none";

export type VizIntent = "comparison" | "distribution" | "relationship" | "composition" | "trend" | "ranking";

export type VizMark = "bar" | "line" | "scatter" | "histogram" | "box";

export interface ApiTransport {
  request<TResponse>(request: ApiRequest): Promise<TResponse>;
  subscribe(request: SseRequest): AsyncIterable<SseEvent>;
}

export interface ApiRequest {
  path: string;
  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  body?: unknown;
  signal?: AbortSignal;
}

export interface SseRequest {
  path: string;
  signal?: AbortSignal;
}

export interface SseEvent {
  event: string;
  id?: string;
  data: unknown;
}

export class PlatformApiClient {
  public constructor(private readonly transport: ApiTransport) {}

  public health(): Promise<HealthResponse> {
    return this.transport.request<HealthResponse>({ path: "/api/v1/platform/health" });
  }

  public events(signal?: AbortSignal): AsyncIterable<SseEvent> {
    return this.transport.subscribe({ path: "/api/v1/platform/events", ...(signal ? { signal } : {}) });
  }
}
