"""Generate the minimal TypeScript public contract from the canonical FastAPI OpenAPI document."""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [
    str(ROOT / "apps" / "api" / "src"),
    *[str(path) for path in (ROOT / "packages").glob("*/python")],
]

from prism_api.main import create_app  # noqa: E402

TARGET = ROOT / "packages" / "api-contracts" / "typescript" / "src" / "generated.ts"


def type_for(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", maxsplit=1)[-1]
    if "anyOf" in schema:
        variants = [type_for(variant) for variant in schema["anyOf"] if variant.get("type") != "null"]
        return " | ".join(dict.fromkeys(variants)) if variants else "unknown"
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if schema.get("type") == "array":
        return f"{type_for(schema.get('items', {}))}[]"
    if schema.get("type") == "object":
        return f"Record<string, {type_for(schema['additionalProperties'])}>" if "additionalProperties" in schema else "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}.get(
        schema.get("type"), "unknown"
    )


def render_model(name: str, schema: dict[str, Any]) -> str:
    if "enum" in schema:
        return f"export type {name} = {type_for(schema)};\n"
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in schema.get("properties", {}).items():
        optional = "" if property_name in required else "?"
        lines.append(f"  {property_name}{optional}: {type_for(property_schema)};")
    return "\n".join([*lines, "}\n"])


def render() -> str:
    openapi = create_app().openapi()
    schemas = openapi["components"]["schemas"]
    # FastAPI's component insertion order can vary with interpreter-level type
    # evaluation. Sorting makes this checked-in artifact deterministic across
    # local development and CI.
    models = "\n".join(render_model(name, schemas[name]) for name in sorted(schemas))
    return f"""/* This file is generated by tools/generate_typescript_contracts.py. Do not edit manually. */

{models}
export interface ApiTransport {{
  request<TResponse>(request: ApiRequest): Promise<TResponse>;
  subscribe(request: SseRequest): AsyncIterable<SseEvent>;
}}

export interface ApiRequest {{
  path: string;
  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  body?: unknown;
  signal?: AbortSignal;
}}

export interface SseRequest {{
  path: string;
  signal?: AbortSignal;
}}

export interface SseEvent {{
  event: string;
  id?: string;
  data: unknown;
}}

export class PlatformApiClient {{
  public constructor(private readonly transport: ApiTransport) {{}}

  public health(): Promise<HealthResponse> {{
    return this.transport.request<HealthResponse>({{ path: "/api/v1/platform/health" }});
  }}

  public events(signal?: AbortSignal): AsyncIterable<SseEvent> {{
    return this.transport.subscribe({{ path: "/api/v1/platform/events", ...(signal ? {{ signal }} : {{}}) }});
  }}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    existing = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if args.check:
        if existing != generated:
            print(
                "Generated TypeScript contract is stale. Run: python tools/generate_typescript_contracts.py"
            )
            print("".join(difflib.unified_diff(existing.splitlines(True), generated.splitlines(True), fromfile="checked-in", tofile="generated")))
            return 1
        return 0
    with TARGET.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
